[package]
name = "client"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
yew = "0.18"
anyhow = { version = "1.0.45" }
utils = { path = "../utils" }

[[bin]]
name = "client"
path = "src/mod.rs"