[package]
name = "Rust-StockTradingSimulator"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "server",  # run `cargo run -p server` or `cargo run --bin server --manifest-path server/Cargo.toml`
    "client",  # run `trunk serve`
]

[[bin]]
name = "server"
path = "server/src/main.rs"

[[bin]]
name = "client"
path = "client/src/main.rs"