FROM rust:latest

RUN apt update
RUN apt install -y libpq-dev

RUN rustup target add wasm32-unknown-unknown
RUN cargo install trunk wasm-bindgen-cli

COPY . .

EXPOSE 5000

CMD trunk --config ./src/bin/client_data/trunk.toml serve
