version: '3.1'
 
services:
 
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - stockdb:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - stocknet
 
  backend:
    image: pv281.azurecr.io/stocks-server:1.0.0
    restart: always
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://pv281:rustrust1!@pv281-stocks.postgres.database.azure.com/postgres?sslmode=require
    networks:
      - stocknet

  web:
    image: pv281.azurecr.io/stocks-server-client:1.0.0
    restart: always
    ports:
      - "5000:5000"



networks:
  stocknet:

volumes:
  stockdb: