version: '3.1'
 
services:
 
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      DATABASE_URL: postgres://postgres:example@localhost:5432/stocks
 
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"