-- SET NOT NULL

ALTER TABLE COMPANY ALTER COLUMN performer_id SET NOT NULL;

ALTER TABLE COMMAND ALTER COLUMN stonker_id SET NOT NULL;
ALTER TABLE COMMAND ALTER COLUMN company_id SET NOT NULL;

ALTER TABLE HISTORY ALTER COLUMN stonker_id SET NOT NULL;
ALTER TABLE HISTORY ALTER COLUMN stock_id SET NOT NULL;

ALTER TABLE STOCK ALTER COLUMN stonker_id SET NOT NULL;
ALTER TABLE STOCK ALTER COLUMN company_id SET NOT NULL;